#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if command -v python &>/dev/null; then
    python "$DIR/infra/scripts/vtt_cli.py" "$@"
elif command -v python3 &>/dev/null; then
    python3 "$DIR/infra/scripts/vtt_cli.py" "$@"
elif command -v py &>/dev/null; then
    py "$DIR/infra/scripts/vtt_cli.py" "$@"
else
    node "$DIR/infra/scripts/vtt_cli.js" "$@"
fi
