import json

with open('scratch/master_mapping.json', 'r', encoding='utf-8') as f:
    mapping = json.load(f)

# Refine composite IDs
refinements = {
    "couro_de_lobo": "wolf_leather",
    "presas_de_lobo": "wolf_fangs",
    "canino_congelante": "freezing_canine",
    "canino_flamejante": "flaming_canine",
    "carne_assada_de_tuctuc": "roasted_tuctuc_meat",
    "carne_assada_de_undino": "roasted_undino_meat",
    "carne_de_undino": "undino_meat",
    "chifre_de_cornara": "cornara_horn",
    "couro_de_cornara": "cornara_leather",
    "couro_de_equiliz": "equiliz_leather",
    "couro_de_ganodonte": "ganodonte_leather",
    "garras_vulcanicas": "volcanic_claws",
    "marfim_de_ganodonte": "ganodonte_ivory",
    "olhos_de_moriu": "moriu_eyes",
    "osso_de_rei_undino": "undino_king_bone",
    "pena_de_moriu": "moriu_feather",
    "pena_de_tuctuc": "tuctuc_feather",
    "pena_de_undino": "undino_feather",
    "sangue_azul": "blue_blood",
    "tromba_de_ganodonte": "ganodonte_trunk",
    # Species splits
    "humano_demonio": "human", # We will handle the split logic in the translation script
    "humano_gran": "human",
    "humano_monstro": "human",
    # Equipment
    "capacete_de_couro": "leather_helmet",
    "chapeu_de_couro": "leather_hat",
    "chapeu_de_couro_de_lobo": "wolf_leather_hat",
    "elmo_de_ferro": "iron_helmet",
    "elmo_de_ossos": "bone_helmet",
    "enfeite_de_palha": "straw_ornament",
    "tiara_de_renda": "lace_headband",
    "turbante_de_pano": "cloth_turban",
    "veu_de_renda": "lace_veil",
    "colete_de_couro": "leather_vest",
    "colete_de_couro_de_lobo": "wolf_leather_vest",
    "jaqueta_de_couro_draconico": "draconic_leather_jacket",
    "peitoral_de_aco": "steel_chestplate",
    "peitoral_de_ferro": "iron_chestplate",
    "peitoral_de_osso": "bone_chestplate",
    "peitoral_de_ossos": "bone_chestplate",
    "sobretudo_de_couro_de_jopopis": "jopopis_leather_overcoat",
    "vestido_de_couro_de_ganlan": "ganlan_leather_dress",
    "vestido_de_pano": "cloth_dress",
    "adaga_gemea_agua": "twin_water_daggers",
    "adaga_gemea_fogo": "twin_fire_daggers",
    "bastao_de_madeira": "wooden_staff",
    "cesta_de_palha": "straw_basket",
    "colher_de_madeira": "wooden_spoon",
    "espada_de_aco": "steel_sword",
    "espada_de_ferro": "iron_sword",
    "espada_de_treino": "training_sword",
    "jarra_de_metal": "metal_jar",
    "taca_de_vidro": "glass_cup",
    "calca_de_couro": "leather_pants",
    "calca_de_couro_de_ganlan": "ganlan_leather_pants",
    "calca_de_couro_de_inoue": "inoue_leather_pants",
    "calca_de_couro_de_lobo": "wolf_leather_pants",
    "calca_de_couro_de_rei_undino": "undino_king_leather_pants",
    "calca_de_pano": "cloth_pants",
    "calca_de_seda": "silk_pants",
    "calca_de_tecido": "fabric_pants",
    "calcas_de_couro_de_equiliz": "equiliz_leather_pants",
    "calcas_reforcadas_com_ossos_de_rei_undino": "undino_king_bone_reinforced_pants",
    "placa_de_ferro": "iron_plate",
    "saia_de_pano": "cloth_skirt",
    "saia_de_renda": "lace_skirt",
    "saia_de_seda": "silk_skirt",
    "bota_de_couro_de_enbarr": "enbarr_leather_boots",
    "bota_de_couro_de_equilliz": "equiliz_leather_boots",
    "protetor_de_ferro": "iron_protector",
    "sandalia_de_fibra": "fiber_sandal",
    "sapatilha_de_okaka": "okaka_shoes",
    "sapatilha_de_pavlova": "pavlova_shoes",
    "sapato_de_areat": "areat_shoes",
    "sapato_de_couro": "leather_shoes",
    "sapato_de_couro_de_lobo": "wolf_leather_shoes",
    "sapato_de_crocohog": "crocohog_shoes",
    "sapato_de_fibra": "fiber_shoes",
    "sapato_de_pano": "cloth_shoes",
    "bracadeira_de_ferro": "iron_bracer",
    "bracelete_de_fibra": "fiber_bracelet",
    "bracelete_de_madeira": "wooden_bracelet",
    "cinto_de_pedra_azul": "blue_stone_belt",
    "fita_de_seda": "silk_ribbon",
    "luva_de_cornara": "cornara_glove",
    "luvas_de_couro_de_ganlan": "ganlan_leather_gloves",
    "pulseira_de_pedra_azul": "blue_stone_bracelet",
    "faixa_de_seda": "silk_sash"
}

mapping.update(refinements)

with open('scratch/master_mapping.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, indent=2, ensure_ascii=False)
